services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./:/next-admin
      - /next-admin/node_modules
      - /next-admin/.next
    ports:
      - 3000:3000
