import Head from 'next/head'
import Image from 'next/image'
import BaseLayout from '@components/app/BaseLayout'

import { FC } from 'react'

const Home: FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis
        quibusdam atque aliquid omnis est quidem nesciunt sint vitae sunt
        voluptatem. Porro repellat consequatur molestias et. Sed aspernatur
        ipsum pariatur qui?
      </BaseLayout>
    </>
  )
}

export default Home
